Fix build, due to Rubocop error
Fixes the error:

```
Offenses:

test/roundtrip/test_rubyc.rb:33:31: C: [Correctable] Style/HashConversion: Prefer literal hash to Hash[key: value, ...].
                parsed_line = Hash[timestamp: Time.now, line: raw_line.to_s]
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test/roundtrip/test_rubyc.rb:40:31: C: [Correctable] Style/HashConversion: Prefer literal hash to Hash[key: value, ...].
                parsed_line = Hash[timestamp: Time.now, line: raw_line.to_s]
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

11 files inspected, 2 offenses detected, 2 offenses auto-correctable
Error: Process completed with exit code 1.
```

which breaks the build.